[tool.poetry]
name = "mygit"
version = "0.1.0"
description = ""
authors = ["Prathamesh Lohakare <prathamesh.lohakare@druva.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
